# https://taskfile.dev

version: '3'

vars:
   CROSS_COMPILE: "aarch64-none-elf-"
   DEVICE_TREE: "zynqmp-zcu102-rev1.0"
   OUT_DIR: "generated/src"
   DIST_DIR: "dist"
   TOOLCHAIN_DIR: "{{.TOOLCHAIN_DIR}}"

tasks:
   get_atf:
     desc: "get atf"
     aliases: [gub]
     vars:
       GIT_VERSION: "bc531ba7e5a365c307c9a4ffdb155641fd7065f8"
     status:
       - cat {{.OUT_DIR}}/.git/HEAD | grep {{.GIT_VERSION}}
     cmds:
      - git clone https://github.com/Xilinx/arm-trusted-firmware.git --depth 1 -b xilinx-v2022.2 {{.OUT_DIR}}

   atf_apply_patch:
     desc: "apply patch to atf source"
     aliases: [appt]
     dir: "{{.OUT_DIR}}"
     cmds:
       - git am {{.PATCH_DIR}}/0001-Disable-LOAD-segment-with-RWX-error.patch
     status:
       - git log | grep "Disable LOAD segment with RWX error"
 
   clean_atf:
     desc: "clean atf source"
     aliases: [cub]
     dir: "{{.OUT_DIR}}"
     env:
       CROSS_COMPILE: "{{.CROSS_COMPILE}}"
     cmds:
       - PATH="{{.TOOLCHAIN_DIR}}/bin:{{.PATH}}" make -j8 CROSS_COMPILE={{.CROSS_COMPILE}} ZYNQMP_CONSOLE=cadence PLAT=zynqmp RESET_TO_BL31=1 distclean

   build_atf:
     desc: "build atf"
     aliases: [bub]
     dir: "{{.OUT_DIR}}"
     env:
       PATH: "{{.TOOLCHAIN_DIR}}/bin:{{.PATH}}"
       CROSS_COMPILE: "{{.CROSS_COMPILE}}"
     cmds:
       - task: get_atf
       - task: atf_apply_patch
       - PATH="{{.TOOLCHAIN_DIR}}/bin:{{.PATH}}" make CROSS_COMPILE={{.CROSS_COMPILE}} ZYNQMP_CONSOLE=cadence bl31 PLAT=zynqmp RESET_TO_BL31=1 DEBUG=1 

   clean_build_atf:
     desc: "clean build atf"
     aliases: [cbub]
     cmds:
       #   - task: get_atf
       - task: clean_atf
       - task: atf_apply_patch
       - task: build_atf

 


