# https://taskfile.dev

version: '3'

vars:
  TOOLCHAIN_BMT: 
    sh: echo "{{.USER_WORKING_DIR}}/toolchain/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf"
  TOP_DIR:
    sh: echo $(pwd)
  QEMU_UG_OUTPUT: "{{.TOP_DIR}}/generated/qemu-ug-examples"
  QEMU_GENERATED: "{{.TOP_DIR}}/generated"

includes:
  toolchain:
    taskfile: ./toolchain/Taskfile.yml
    internal: true
  qemu: 
    taskfile: ./qemu/Taskfile.yml
    dir: ./qemu
    internal: true
  ramfs: 
    taskfile: ./filesystems/initramfs/Taskfile.yml
    dir: ./filesystems/initramfs/
    internal: true
  rootfs: 
    taskfile: ./filesystems/rootfs/Taskfile.yml
    dir: ./filesystems/rootfs/
    internal: true
  kernel: 
    taskfile: ./kernel/Taskfile.yml
    dir: ./kernel
    internal: true
  earlyboot: 
    taskfile: ./bootloader/Taskfile.yml
    dir: ./bootloader
    internal: true
    vars:
      TOOLCHAIN_DIR: "{{.TOOLCHAIN_BMT}}"
      BASE_DIR: "{{.ROOT_DIR}}"
      HW_DESC_DIR: "{{.TOP_DIR}}/system_hw_description"
      DIR_BOOTLOADER: "{{.TOP_DIR}}/bootloader"


tasks:
  build_flash_stripe_util:
    aliases: [bfsu]
    desc: "clone and build flash stripe utility"
    dir: "{{.QEMU_UG_OUTPUT}}"
    internal: true
    cmds:
      - dpkg -l build-essential >/dev/null && echo "continue" || sudo apt install build-essential
      - git clone https://github.com/Xilinx/qemu-ug-examples.git qemu_uge
      - cd qemu_uge && git checkout 8b3082b0a50cdc79e0a8e343dd845d61c1285f6b 
      - cd qemu_uge/flash_stripe_utilities/ && gcc flash_stripe.c -o flash_strip_bw -DFLASH_STRIPE_BW
    sources:
      - qemu_uge/flash_stripe_utilities/flash_strip.c
    generates:
      - qemu_uge/flash_stripe_utilities/flash_strip_bw


  build_qemu_qspi_drive:
    dir: qemu
    deps: [build_flash_stripe_util]
    aliases: [bqqd]
    desc: "build qspi persistent memory fo qemu (NOR) "
    summary: |
      build qspi persistent memory fo qemu (NOR)
      zynq ultrascale only support 128 MB QSPI in dual parallel mode
      so 2 virtual NOR memory devices need to be created, each of it
    vars:
      bin_name: qemu_qspi.bin
      kernel: "../kernel/Image.itb"
      #initramfs: "../filesystems/initramfs.cpio.gz"
      bootbin: "{{.ROOT_DIR}}/bootloader/generated/boot.bin"
      bootscr: "{{.ROOT_DIR}}/bootloader/boot.scr"
      flash_stripe: "{{.QEMU_UG_OUTPUT}}/qemu_uge/flash_stripe_utilities/flash_strip_bw"
    cmds:
      - task: toolchain:export_bmt
      - task: earlyboot:build_bootbin
      - task: build_itb
      - dd if=/dev/zero of={{.bin_name}} bs=128M count=1
      - dd if={{.bootbin}} of={{.bin_name}} bs=1 seek=0 conv=notrunc
      - dd if={{.bootscr}} of={{.bin_name}} bs=1 seek=65536000 conv=notrunc #offset 0x3e80000
      - dd if={{.kernel}} of={{.bin_name}} bs=1 seek=15990784 conv=notrunc #offset 0xF40000
      - "{{.flash_stripe}} qemu_qspi.bin qemu_qspi_low.bin qemu_qspi_high.bin"

  create_sd_drive:
    dir: drives
    desc: "create sd drive"
    deps: [qemu:build_qemu]
    internal: true
    vars:
      sd_drive_bin_name: qemu_sd.img
      qemu_img: "{{.ROOT_DIR}}/qemu/generated/src/build/qemu-img"
      qemu_nbd: "{{.ROOT_DIR}}/qemu/generated/src/build/qemu-nbd"
    cmds:
      - sudo apt install nbd-client nbd-server
      - sudo modprobe nbd #Load the necessary kernel modules
      - sudo {{.qemu_img}} create {{.sd_drive_bin_name}} 2G
      - sudo {{.qemu_nbd}} -f raw -c /dev/nbd0 {{.sd_drive_bin_name}} # connect image to network block device nbd
        #- qemu-nbd {{.sd_drive_bin_name}} & # connect image to network block device nbd
        #- sudo nbd-client localhost 1024 /dev/nbd0 #Connect to the disk

  partition_sd_drive:
    aliases: [psd]
    internal: true
    dir: drives
    deps: [create_sd_drive]
    desc: "partition sd drive"
    cmds:
      - sudo sfdisk /dev/nbd0 < sd_card.layout
        #      - sudo fdisk /dev/nbd0 # for manually partitionning
      - sudo mkfs.vfat /dev/nbd0p1
      - sudo mkfs.ext3 /dev/nbd0p2

  disconnect_nbd:
    desc: "Once the files are copied, disconnect the nbd connection"
    internal: true
    deps: [qemu:build_qemu]
    vars:
      qemu_nbd: "{{.ROOT_DIR}}/qemu/generated/src/build/qemu-nbd"
    cmds:
      - sudo {{.qemu_nbd}} -d /dev/nbd0
   
 
  build_qemu_sd_drive:
    aliases: [bqsd]
    desc: "build qemu sd drive"
    vars:
      rootfs: "{{.TASKFILE_DIR}}/filesystems/rootfs/generated/rootfs/rootfs.ext3"
    cmds:
      - task: partition_sd_drive
      - task: rootfs:default
      - sudo dd if={{.rootfs}} of=/dev/nbd0p2 bs=512M count=1
      - task: disconnect_nbd
  
  build_itb:
    dir: kernel
    aliases: [bitb]
    internal: true
    desc: "build linux itb image"
    vars:
      kernel: "generated/src/arch/arm64/boot/Image"
      dtb: "device-tree/zynqmp-zcu102-rev1.0.dtb"
      initramfs: "{{.ROOT_DIR}}/filesystems/initramfs/generated/initramfs.cpio.gz"
    sources:
      - "{{.kernel}}"
      - "{{.dtb}}"
      - "{{.initramfs}}"
    generates:
      - "Image.itb"
    cmds:
     - dpkg -l | grep u-boot-tools && echo "continue" || sudo apt install u-boot-tools -y  #for mkimage
     - task: kernel:bk
     - task: ramfs:bir
     - ln -sf {{.kernel}} Image
     - ln -sf {{.dtb}} kernel.dtb
     - ln -sf {{.initramfs}} initramfs.cpio.gz
     - mkimage -f zcu102.its Image.itb

  start_os_on_qemu:
    aliases: [sooq]
    desc: "start os on qemu emulator"
    vars:
      drives_dir: "{{.ROOT_DIR}}/drives"
      qemu_dir: "{{.ROOT_DIR}}/qemu"
      qemu_xilinx: "{{.ROOT_DIR}}/qemu/generated/src/build"
      pmu_dtb: "{{.ROOT_DIR}}/bootloader/pmu/generated/src/LATEST/MULTI_ARCH/zynqmp-pmu.dtb"
      pmu_rom: "{{.ROOT_DIR}}/bootloader/pmu/generated/PMU_ROM/pmu-rom.elf"
      hw_dtb: "{{.ROOT_DIR}}/bootloader/pmu/generated/src/LATEST/MULTI_ARCH/zcu102-arm.dtb"
      fsbl: "{{.ROOT_DIR}}/bootloader/coreboot/generated/src/build/fsboot_a53_zc102.elf"
      qemu_shmdir: "/tmp/tmpmor_aano"
      QSPI_24BIT: "1"
      QSPI_24BIT_INDEX: "0"
      QSPI_32BIT: "2"
      QSPI_32BIT_INDEX: "1"
    cmds:
      - test -d {{.qemu_shmdir}} && rm -rvf {{.qemu_shmdir}}
      - test -d {{.qemu_shmdir}} || mkdir -p {{.qemu_shmdir}}
      - touch {{.qemu_shmdir}}/qemu-rport-_pmu@0
      - |
        sudo {{.qemu_xilinx}}/qemu-system-microblazeel -M microblaze-fdt \
        -display none \
        -hw-dtb {{.pmu_dtb}} \
        -kernel {{.pmu_rom}} \
        -machine-path {{.qemu_shmdir}} \
        & \
        sudo {{.qemu_xilinx}}/qemu-system-aarch64 \
        -machine arm-generic-fdt \
        -m 4096 \
        -nographic \
        -chardev stdio,mux=on,id=char0,logfile={{.QEMU_GENERATED}}/os_boot.log,signal=off \
        -mon chardev=char0,mode=readline \
        -serial chardev:char0 \
        -hw-dtb {{.hw_dtb}} \
        -global xlnx,zynqmp-boot.cpu-num=0 \
        -global xlnx,zynqmp-boot.use-pmufw=false \
        -device loader,file={{.fsbl}},cpu-num=0 \
        -drive file={{.qemu_dir}}/qemu_qspi_low.bin,if=mtd,format=raw,index=0 \
        -drive file={{.qemu_dir}}/qemu_qspi_high.bin,if=mtd,format=raw,index=1 \
        -drive file={{.drives_dir}}/qemu_sd.img,if=sd,format=raw,index=1 \
        -boot mode={{.QSPI_32BIT}} \
        -machine-path {{.qemu_shmdir}}

  start_fsbl_on_qemu_debug:
    aliases: [sfoqd]
    desc: "start fsbl on qemu emulator with -gdb tcp::1234 (arg -s) "
    summary: |
      in order to use it, go to fsbl dir and 
      start gdb e.g aarch64-none-elf-gdb fsbl_a53.elf
      then perform "target remote :1234" for remote
      debugging (gdb_on_host <-- tcp:1234 --> fsbl on qemu)
    vars:
      qemu_dir: "{{.ROOT_DIR}}/qemu"
      qemu_xilinx: "{{.ROOT_DIR}}/qemu/generated/src/build"
      pmu_dtb: "{{.ROOT_DIR}}/bootloader/pmu/generated/src/LATEST/MULTI_ARCH/zynqmp-pmu.dtb"
      pmu_rom: "{{.ROOT_DIR}}/bootloader/pmu/generated/PMU_ROM/pmu-rom.elf"
      hw_dtb: "{{.ROOT_DIR}}/bootloader/pmu/generated/src/LATEST/MULTI_ARCH/zcu102-arm.dtb"
      fsbl: "{{.ROOT_DIR}}/bootloader/coreboot/generated/src/build/fsboot_a53_zc102.elf"
      qemu_shmdir: "/tmp/tmpmor_aano"
      QSPI_24BIT: "1"
      QSPI_24BIT_INDEX: "0"
      QSPI_32BIT: "2"
      QSPI_32BIT_INDEX: "1"
    cmds:
      - test -d {{.qemu_shmdir}} && rm -rvf {{.qemu_shmdir}}
      - test -d {{.qemu_shmdir}} || mkdir -p {{.qemu_shmdir}}
      - touch {{.qemu_shmdir}}/qemu-rport-_pmu@0
      - |
        sudo {{.qemu_xilinx}}/qemu-system-microblazeel -M microblaze-fdt \
        -display none \
        -hw-dtb {{.pmu_dtb}} \
        -kernel {{.pmu_rom}} \
        -machine-path {{.qemu_shmdir}} \
        & \
        sudo {{.qemu_xilinx}}/qemu-system-aarch64 \
        -machine arm-generic-fdt \
        -m 4096 \
        -s -S \
        -nographic \
        -chardev stdio,mux=on,id=char0,logfile={{.QEMU_GENERATED}}/os_boot_debug.log,signal=off \
        -mon chardev=char0,mode=readline \
        -serial chardev:char0 \
        -hw-dtb {{.hw_dtb}} \
        -global xlnx,zynqmp-boot.cpu-num=0 \
        -global xlnx,zynqmp-boot.use-pmufw=false \
        -device loader,file={{.fsbl}},cpu-num=0 \
        -drive file={{.qemu_dir}}/qemu_qspi_low.bin,if=mtd,format=raw,index=0 \
        -drive file={{.qemu_dir}}/qemu_qspi_high.bin,if=mtd,format=raw,index=1 \
        -boot mode={{.QSPI_32BIT}} \
        -machine-path {{.qemu_shmdir}}


  build_and_start_os:
    aliases: [basos]
    desc: "build os and launch it on qemu emulator"
    cmds:
      - task: qemu:build_qemu
      - task: build_qemu_qspi_drive
      - task: build_qemu_sd_drive
      - task: start_os_on_qemu
 

