# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  YOCTO_DEPLOY_DIR: "{{.HOME}}/yocto/ulrr/generated/tmp/deploy/images/zcu102-zynqmp"

tasks:
  get_host_dependencies:
    desc: "retrieve build dependencies"
    cmds:
      - dpkg -l | grep ncurses-dev && echo "continue" || sudo apt install ncurses-dev
 
  get_dropbear:
    dir: generated
    desc: "get dropbear"
    cmds:
      - wget https://matt.ucc.asn.au/dropbear/releases/dropbear-2022.83.tar.bz2
      - tar -xjf dropbear-2022.83.tar.bz2
    status:
      - test -f dropbear-2022.83.tar.bz2

 
  get_busybox:
    dir: generated
    desc: "get busybox"
    cmds:
      - wget https://busybox.net/downloads/busybox-1.36.1.tar.bz2
      - tar -xjf busybox-1.36.1.tar.bz2
    status:
      - test -f busybox-1.36.1.tar.bz2

  build_busybox:
    dir: generated/busybox-1.36.1
    desc: "build busybox"
    deps: [get_busybox]
    cmds:
      - task: get_host_dependencies
      - make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
      - make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
    status:
      - cat .config | grep "CONFIG_STATIC=y"
      - file busybox | grep "ELF 64-bit LSB executable, ARM aarch64"

  build_dropbear:
    dir: generated/dropbear-2022.83
    desc: "build_and_install dropbear"
    deps: [get_dropbear]
    cmds:
      - ./configure --host=aarch64-linux-gnu --prefix=/ --disable-zlib --disable-utmp --disable-lastlog --disable-wtmp --disable-loginfunc --disable-pam --enable-static CC=aarch64-linux-gnu-gcc LD=aarch64-linux-gnu-ld
      - make
    status:

  install_busybox:
    dir: generated/busybox-1.36.1
    desc: "install busybox"
    deps: [build_busybox]
    cmds:
      - make ARCH=aarch64 CROSS_COMPILE=aarch64-linux-gnu- install CONFIG_PREFIX=../initramfs

  install_dropbear:
    dir: generated/dropbear-2022.83
    desc: "install dropbear"
    deps: [build_dropbear]
    cmds:
      - make install DESTDIR=../initramfs

  install_rootfs_folders:
    dir: generated/initramfs
    desc: "install initramfs folders"
    deps: [install_busybox]
    cmds:
      - mkdir proc sys dev etc etc/init.d usr/lib home home/root root
      - touch init
      - chmod +x init
      - echo "#!/bin/sh" > init
      - echo "mount -t proc none /proc" >> init
      - echo "mount -t sysfs none /sys" >> init
      - echo "mknod /dev/mmcblk0 b 179 0" >> init
      - echo "mkdir -p mnt/bin" >> init
      - echo "mount /dev/mmcblk0 mnt/bin" >> init
      - echo "mkdir -p mnt/rootfs" >> init
      - echo "mount -t ext3 mnt/bin/rootfs.ext3 mnt/rootfs/" >> init
      - echo "chroot mnt/rootfs/ bin/bash" >> init
      - |
        echo "
        cat <<!
        Boot took $(cut -d ' ' -f1 /proc/uptime) seconds
        
                _       _     __ _                  
                  /\/\ (_)_ __ (_)   / /(_)_ __  _   ___  __
                   /    \| | '_ \| |  / / | | '_ \| | | \ \/ /
                   / /\/\ \ | | | | | / /__| | | | | |_| |>  < 
                   \/    \/_|_| |_|_| \____/_|_| |_|\__,_/_/\_\ 
        
        
                   Welcome to ulrr_linux
        
        !
        exec /bin/sh
        " >> init

  build_initramfs:
    aliases: [bir]
    dir: generated/initramfs
    desc: "build initramfs folders"
    cmds:
      - test -d ../initramfs && rm -r * || echo "continue"
      - task: install_rootfs_folders
      - find . | cpio --quiet -H newc -o | gzip -9 -n > ../initramfs.cpio.gz 
  
