# https://taskfile.dev

version: '3'

vars:
   BRANCH: "xlnx_rel_v2022.2"
   DIR_BOOTLOADER: '{{.DIR_BOOTLOADER| default "generated"}}'
   BOOTGEN_OUT_DIR: "{{.DIR_BOOTLOADER}}/bootgen/src"


tasks:
  clean_comp:
    dir: "{{.comp_dir}}"
    silent: true
    cmds:
      - make clean

  create_bootgen_folder:
    desc: "create bootgen folder"
    cmds:
      - test -d {{.DIR_BOOTLOADER}}/bootgen || mkdir {{.DIR_BOOTLOADER}}/bootgen
      - test -d {{.BOOTGEN_OUT_DIR}} || mkdir {{.BOOTGEN_OUT_DIR}}
 
  get_bl:
    desc: "get bootgen"
    aliases: [gbg]
    status:
      - cat {{.BOOTGEN_OUT_DIR}}/.git/HEAD | grep {{.BRANCH}}
    cmds:
      - task: create_bootgen_folder
      - test -d {{.BOOTGEN_OUT_DIR}} && rm -rf {{.BOOTGEN_OUT_DIR}} || echo "continue"
      - git clone https://github.com/Xilinx/bootgen.git --depth 1 -b {{.BRANCH}} {{.BOOTGEN_OUT_DIR}}

  build_bg:
    aliases: [bbg]
    desc: "build bootgen"
    status:
      - readelf -h {{.BOOTGEN_OUT_DIR}}/bootgen | grep "Advanced Micro Devices X86-64"
    cmds:
      - dpkg -l libssl-dev >/dev/null && echo "continue" || sudo apt install -f libssl-dev
      - cd {{.BOOTGEN_OUT_DIR}} && make

  clean_bl:
    aliases: [cbg]
    desc: "clean bootgen"
    cmds:
      - task: clean_comp
        vars:
          comp_dir: "{{.BOOTGEN_OUT_DIR}}"



