# https://taskfile.dev

version: '3'

vars:
   QEMU_OUT_DIR: "{{.USER_WORKING_DIR}}/generated/qemu/src"
   NPROC:
     sh:
       echo $(nproc)

tasks:
  get_dependencies:
    desc: "retrieve qemu host dependencies"
    internal: true
    cmds:
      - dpkg -l | grep ninja-build >/dev/null && echo "continue" || (sudo apt update && sudo apt install -y ninja-build)
      - dpkg -l | grep pkg-config >/dev/null && echo "continue" || (sudo apt update && sudo apt install -y pkg-config)
      - dpkg -l | grep libglib2.0-dev >/dev/null && echo "continue" || (sudo apt update && sudo apt install -y libglib2.0-dev)
      - dpkg -l | grep libpixman-1-dev >/dev/null && echo "continue" || (sudo apt update && sudo apt install -y libpixman-1-dev)
      - dpkg -l | grep build-essential >/dev/null && echo "continue" || (sudo apt update && sudo apt install -y build-essential)

  clean_qemu:
    desc: "clean qemu"
    deps: [get_qemu]
    cmds:
      - cd {{.QEMU_OUT_DIR}} && make clean

  create_qemu_folder:
    desc: "create qemu folder"
    internal: true
    cmds:
      - test -d {{.USER_WORKING_DIR}}/generated || mkdir {{.USER_WORKING_DIR}}/generated
      - test -d {{.USER_WORKING_DIR}}/generated/qemu || mkdir {{.USER_WORKING_DIR}}/generated/qemu
      - test -d {{.QEMU_OUT_DIR}} || mkdir {{.QEMU_OUT_DIR}}

  get_qemu:
    desc: "get qemu"
    vars:
      GIT_VERSION: "xlnx_rel_v2022.2"
    status:
      - cat {{.QEMU_OUT_DIR}}/.git/HEAD | grep {{.GIT_VERSION}}
    cmds:
      - task: create_qemu_folder
      - test -d {{.QEMU_OUT_DIR}} && rm -rf {{.QEMU_OUT_DIR}} || echo "continue"
      - git clone https://github.com/Xilinx/qemu.git --depth 1 -b xlnx_rel_v2022.2 {{.QEMU_OUT_DIR}}

  configure_qemu:
    desc: "configure qemu"
    deps: [get_qemu]
    status:
      - readelf -h {{.QEMU_OUT_DIR}}/build/qemu-system-aarch64 | grep "7f 45 4c 46 02 01 01 03 00 00 00 00 00 00 00 00"
    cmds:
      - task: get_dependencies
      - |
        cd {{.QEMU_OUT_DIR}} && ./configure --target-list=aarch64-softmmu,microblazeel-softmmu \
        --enable-fdt \
        --disable-kvm \
        --disable-xen
 
  build_qemu:
    desc: "build qemu"
    deps: [configure_qemu]
    cmds:
      - cd {{.QEMU_OUT_DIR}} && make -j{{.NPROC}}
    status:
      - readelf -h {{.QEMU_OUT_DIR}}/build/qemu-system-aarch64 | grep "7f 45 4c 46 02 01 01 03 00 00 00 00 00 00 00 00"


  clean_build_qemu:
    desc: "clean build qemu"
    cmds:
      - task: clean_qemu
      - task: build_qemu


