# https://taskfile.dev

version: '3'

vars:
  TOOLC_DIR:
    sh: echo "{{.USER_WORKING_DIR}}/toolchain"

  TOOLCHAIN_BMT:
    sh: echo "{{.USER_WORKING_DIR}}/toolchain/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf"

tasks:
  get_bmt:
    dir: toolchain
    desc: "retrieve and install bare metal toolchain"
    cmds:
      - curl -Lo gcc-arm-none-elf.tar.xz https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
      - tar xf gcc-arm-none-elf.tar.xz
      - rm -rf gcc-arm-none-elf.tar.xz
    status:
      - test -d arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf
      - test -f arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/12.2.rel1-x86_64-aarch64-none-elf-manifest.txt

  export_bmt:
    deps: [get_bmt]
    desc: "export bare metal toolchain into the environment"
    env:
      PATH: "{{.TOOLCHAIN_BMT}}/bin:{{.PATH}}"
      CROSS_COMPILE: "aarch64-none-elf-"
    cmds:
      - echo "{{.TOOLC_DIR}}"
      - echo "{{.TOOLCHAIN_BMT}}"

  default:
    deps:
      - task: export_bmt


