# https://taskfile.dev

version: '3'

vars:
  TOOLC_DIR: "{{.USER_WORKING_DIR}}/generated/toolchain"

  TOOLCHAIN_BMT:
    sh: echo "{{.USER_WORKING_DIR}}/generated/toolchain/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf"

tasks:
  prepare_folder:
    desc: "create folder"
    internal: true
    cmds:
      - test -d {{.USER_WORKING_DIR}}/generated || mkdir {{.USER_WORKING_DIR}}/generated
      - test -d {{.TOOLC_DIR}} || mkdir {{.TOOLC_DIR}}
  
  get_bmt:
    desc: "retrieve and install bare metal toolchain"
    cmds:
      - cd {{.TOOLC_DIR}} && touch testchai.uio
      - cd {{.TOOLC_DIR}} && curl -Lo gcc-arm-none-elf.tar.xz https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
      - cd {{.TOOLC_DIR}} && tar xf gcc-arm-none-elf.tar.xz
      - cd {{.TOOLC_DIR}} && rm -rf gcc-arm-none-elf.tar.xz
    status:
      - test -d {{.TOOLC_DIR}}/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf
      - test -f {{.TOOLC_DIR}}/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/12.2.rel1-x86_64-aarch64-none-elf-manifest.txt

  export_bmt:
    deps: [get_bmt]
    desc: "export bare metal toolchain into the environment"
    env:
      PATH: "{{.TOOLCHAIN_BMT}}/bin:{{.PATH}}"
      CROSS_COMPILE: "aarch64-none-elf-"
    cmds:
      - echo "{{.TOOLC_DIR}}"
      - echo "{{.TOOLCHAIN_BMT}}"

  default:
    deps:
      - task: prepare_folder
      - task: export_bmt


